version: "3.8"

services:
  strapi:
    build: ./cms
    container_name: strapi
    ports:
      - "1337:1337"
    volumes:
      - ./cms:/app
      - /app/node_modules
    environment:
      NODE_ENV: production
  
  frontend:
    build: ./frontend
    container_name: nextjs
    ports:
      - "3000:3000"
    depends_on:
      - strapi